#!/usr/bin/env bash
# build-adapters.sh
# Generates AI-tool-specific instruction files from the canonical rules/ directory.
#
# Usage:
#   ./scripts/build-adapters.sh [--output-dir DIR]
#
# Options:
#   --output-dir DIR   Root directory to write adapter files into.
#                      Defaults to the repo root (parent of this script's directory).
#
# Output files (relative to --output-dir):
#   .github/copilot-instructions.md   GitHub Copilot
#   .cursor/rules/standards.mdc       Cursor
#   .windsurf/rules/rules.md          Windsurf (newer)
#   .windsurfrules                    Windsurf (legacy) + Cline (reads this natively)

set -euo pipefail

# ── Exit handlers ─────────────────────────────────────────────────────────────

# Fires on every exit path: normal completion, set -e early exit, and Ctrl+C.
# Keeps the Git Bash window open when the script is double-clicked.
_on_exit() {
  local code=$?
  echo ""
  [[ $code -ne 0 ]] && echo "  ✗ Script exited with error (code ${code})."
  read -n 1 -s -r -p "Press any key to close..."
  echo ""
}
trap '_on_exit' EXIT

# ── Resolve paths ─────────────────────────────────────────────────────────────

# Directory of this script → parent is the repo root → rules/ lives there
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd -P)"
RULES_DIR="${REPO_ROOT}/rules"

# Parse --output-dir argument (default: repo root, resolved from script location)
OUTPUT_DIR="${REPO_ROOT}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)
      OUTPUT_DIR="$(cd "$2" && pwd -P)"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

# ── Helpers ───────────────────────────────────────────────────────────────────

# Strip YAML frontmatter (--- ... ---) from the top of a file.
# Handles files both with and without frontmatter safely.
strip_frontmatter() {
  local file="$1"
  awk '
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/   { in_fm = 0; next }
    !in_fm                         { print }
  ' "$file"
}

# Concatenate all rule files with general.md first, then the rest sorted.
# Each file is separated by a Markdown horizontal rule.
build_combined_content() {
local first=1
  local -a files=()

  # 1. Add general.md first
  [[ -f "${RULES_DIR}/general.md" ]] && files+=("${RULES_DIR}/general.md")

  # 2. Add others alphabetically (ignoring general.md)
  # Using a glob is safer and more portable than parsing ls
  for f in "${RULES_DIR}"/*.md; do
    [[ -e "$f" ]] || continue # Handle empty directory
    [[ "$(basename "$f")" == "general.md" ]] && continue
    files+=("$f")
  done

  for f in "${files[@]}"; do
    if [[ $first -eq 0 ]]; then
      echo ""
      echo "---"
      echo ""
    fi
    strip_frontmatter "$f"
    first=0
  done
}

# Write a file, creating parent directories as needed, and print a status line.
write_file() {
  local dest="$1"
  local content="$2"

  mkdir -p "$(dirname "$dest")"

  # Use printf to ensure no trailing slash/backslash issues and consistent LF
  printf '%s\n' "$content" > "$dest"

  # Fallback for realpath if not installed
  if command -v realpath >/dev/null 2>&1; then
    local rel_path=$(realpath --relative-to="${OUTPUT_DIR}" "$dest" 2>/dev/null || echo "$dest")
  else
    # Simple fallback: just show the basename or absolute path
    local rel_path="${dest#$OUTPUT_DIR/}"
  fi

  echo "  ✓ $rel_path"
}

# ── Build ─────────────────────────────────────────────────────────────────────

echo "Building adapter files from: ${RULES_DIR}"
echo "Output directory:            ${OUTPUT_DIR}"
echo ""

COMBINED="$(build_combined_content)"
GENERATED_NOTICE='<!-- This file is AUTO-GENERATED by scripts/build-adapters.sh -->
<!-- Edit rules/ in the skill repository, then re-run the script. -->
'

# ── 1. GitHub Copilot ─────────────────────────────────────────────────────────
# Plain Markdown. No frontmatter.
write_file \
  "${OUTPUT_DIR}/.github/copilot-instructions.md" \
  "${GENERATED_NOTICE}
${COMBINED}"

# ── 2. Cursor (.mdc) ──────────────────────────────────────────────────────────
# Requires its own YAML frontmatter (description / globs / alwaysApply).
# alwaysApply: true → rule is attached to every session regardless of open files.
CURSOR_FRONTMATTER='---
# AUTO-GENERATED — edit rules/ in the skill repository and re-run build-adapters.sh
description: "Personal coding standards — general principles, frontend, JS/TS, Python"
globs: ""
alwaysApply: true
---'

write_file \
  "${OUTPUT_DIR}/.cursor/rules/standards.mdc" \
  "${CURSOR_FRONTMATTER}

${COMBINED}"

# ── 3. Windsurf (newer: .windsurf/rules/rules.md) ────────────────────────────
# Plain Markdown. No frontmatter. 12,000 character soft limit.
write_file \
  "${OUTPUT_DIR}/.windsurf/rules/rules.md" \
  "${GENERATED_NOTICE}
${COMBINED}"

# ── 4. Windsurf legacy + Cline (.windsurfrules) ───────────────────────────────
# Cline reads .windsurfrules natively, so this single file covers both tools.
# Plain Markdown. No frontmatter.
write_file \
  "${OUTPUT_DIR}/.windsurfrules" \
  "${GENERATED_NOTICE}
${COMBINED}"

# ── Length warning ────────────────────────────────────────────────────────────
CHAR_COUNT="${#COMBINED}"
if [[ $CHAR_COUNT -gt 12000 ]]; then
  echo ""
  echo "  ⚠ Combined content is ${CHAR_COUNT} characters."
  echo "    Windsurf has a ~12,000 character soft limit for rules files."
  echo "    Consider splitting into multiple focused skills."
fi

echo ""
echo "Done."
